module Cities
CITIES = [
  "A Coruña",
  "Aachen",
  "Aarhus",
  "Abbeville",
  "Aberdeen (UK)",
  "Aberdeen (South Dakota)",
  "Aberdeen (Washington)",
  "Abidjan",
  "Abilene",
  "Abu Dhabi",
  "Abuja",
  "Acapulco",
  "Accra",
  "Adamstown",
  "Addis Ababa",
  "Adelaide",
  "Adelboden",
  "Agadir",
  "Agde",
  "Agen",
  "Agios Nikolaos",
  "Agra",
  "Agrigento",
  "Agropoli",
  "Ahmedabad",
  "Aigues-Mortes",
  "Aix-en-Provence",
  "Aix-les-Bains",
  "Ajaccio",
  "Ajman",
  "Akron",
  "Al Ain",
  "Alanya",
  "Alaró",
  "Albacete",
  "Albany",
  "Albenga",
  "Albi",
  "Albufeira",
  "Albuquerque",
  "Alcudia",
  "Aleppo",
  "Alessandria",
  "Ålesund",
  "Alexandria",
  "Algeciras",
  "Alghero",
  "Algiers",
  "Alicante",
  "Alkmaar",
  "Allentown",
  "Almaty",
  "Alofi",
  "Alpe d'Huez",
  "Alta Badia",
  "Altea",
  "Altoona",
  "Amalfi",
  "Amarillo",
  "Amersfoort",
  "Amiens",
  "Amman",
  "Amsterdam",
  "Anaheim",
  "Anchorage",
  "Ancona",
  "Andalo",
  "Andermatt",
  "Andorra la Vella",
  "Andratx",
  "Andria",
  "Angers",
  "Angoulême",
  "Ankara",
  "Ann Arbor",
  "Annapolis",
  "Annecy",
  "Antalya",
  "Antananarivo",
  "Antibes",
  "Antwerp",
  "Anzio",
  "Ao Nang",
  "Aosta",
  "Apeldoorn",
  "Apia",
  "Appleton",
  "Aqaba",
  "Aracaju",
  "Arcachon",
  "Arenzano",
  "Arezzo",
  "Argostoli",
  "Arica",
  "Arles",
  "Arlington (Virginia)",
  "Arlington (Texas)",
  "Armagh",
  "Arnhem",
  "Arosa",
  "Arras",
  "Arrecife",
  "Artà",
  "Asbury Park",
  "Ascoli Piceno",
  "Ascona",
  "Ashdod",
  "Ashgabat",
  "Ashkelon",
  "Asmara",
  "Aspen",
  "Asti",
  "Astoria",
  "Asunción",
  "Atafu",
  "Athens",
  "Athlone",
  "Atlanta",
  "Atlantic City",
  "Auckland",
  "Augsburg",
  "Augusta (Georgia)",
  "Augusta (Maine)",
  "Aurora (Colorado)",
  "Aurora (Illinois)",
  "Austin",
  "Auxerre",
  "Avalon (California)",
  "Avalon (New Jersey)",
  "Avarua",
  "Aveiro",
  "Avellino",
  "Avignon",
  "Avila Beach",
  "Avoriaz",
  "Axamer Lizum",
  "Ayia Napa",
  "Azusa",
  "Bad Gastein",
  "Bad Hofgastein",
  "Baden",
  "Baghdad",
  "Baiona",
  "Bakersfield",
  "Baku",
  "Baltimore",
  "Bamako",
  "Bandar Seri Begawan",
  "Bandol",
  "Bangalore",
  "Bangkok",
  "Bangor",
  "Bangui",
  "Banjul",
  "Bar",
  "Bar Harbor",
  "Barcelona",
  "Bari",
  "Barletta",
  "Barstow",
  "Basel",
  "Basseterre",
  "Basse-Terre",
  "Bastia",
  "Bata",
  "Bath",
  "Baton Rouge",
  "Batumi",
  "Bayonne",
  "Beaulieu-sur-Mer",
  "Beaumont",
  "Beaune",
  "Beersheba",
  "Beijing",
  "Beirut",
  "Belfast",
  "Belfort",
  "Belgrade",
  "Belize City",
  "Bellingham",
  "Bellinzona",
  "Belluno",
  "Belmopan",
  "Belo Horizonte",
  "Bemidji",
  "Benalmadena",
  "Bend",
  "Bendigo",
  "Benevento",
  "Benicàssim",
  "Benidorm",
  "Bergamo",
  "Bergen",
  "Bergerac",
  "Berkeley",
  "Berlin",
  "Bern",
  "Besançon",
  "Bethlehem",
  "Beverly Hills",
  "Béziers",
  "Biarritz",
  "Biel/Bienne",
  "Bielefeld",
  "Biella",
  "Bilbao",
  "Billings",
  "Biloxi",
  "Birmingham (UK)",
  "Birmingham (U.S.)",
  "Bishkek",
  "Bismarck",
  "Bissau",
  "Blanes",
  "Bled",
  "Blois",
  "Bloomington",
  "Blumenau",
  "Boca Chica",
  "Boca Raton",
  "Bochum",
  "Bodrum",
  "Bogotá",
  "Boise",
  "Bologna",
  "Bolzano",
  "Bonifacio",
  "Bonn",
  "Bordeaux",
  "Bordighera",
  "Bormio",
  "Boston",
  "Boulder",
  "Boulogne-sur-Mer",
  "Bourges",
  "Bowling Green",
  "Boynton Beach",
  "Bozeman",
  "Bradenton",
  "Bradford",
  "Braga",
  "Brampton",
  "Brasilia",
  "Bratislava",
  "Braunschweig",
  "Brazzaville",
  "Breda",
  "Bregenz",
  "Brela",
  "Bremen",
  "Bremerhaven",
  "Brescia",
  "Brest",
  "Briançon",
  "Bridgeport",
  "Bridgetown",
  "Brighton",
  "Brindisi",
  "Brisbane",
  "Bristol",
  "Brixen",
  "Brixental",
  "Brno",
  "Brookings",
  "Brownsville",
  "Bruges",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Budva",
  "Buenos Aires",
  "Buffalo",
  "Bujumbura",
  "Burgas",
  "Burlington",
  "Burnt Pine",
  "Butte",
  "Cabo San Lucas",
  "Cadaqués",
  "Cádiz",
  "Caen",
  "Cagliari",
  "Cagnes-sur-Mer",
  "Cairns",
  "Cala Bona",
  "Cala d'Or",
  "Cala Millor",
  "Cala Ratjada",
  "Calais",
  "Calella",
  "Calgary",
  "Cali",
  "Caloundra",
  "Calp",
  "Caltanissetta",
  "Calvi",
  "Cambridge (UK)",
  "Cambridge (U.S.)",
  "Cambrils",
  "Camden",
  "Campinas",
  "Campobasso",
  "Can Pastilla",
  "Can Picafort",
  "Canazei",
  "Canberra",
  "Cancun",
  "Cannes",
  "Cannon Beach",
  "Canterbury",
  "Canton",
  "Canyamel",
  "Capdepera",
  "Cape Canaveral",
  "Cape Coral",
  "Cape May",
  "Cape Town",
  "Capitola",
  "Carbonia",
  "Carcassonne",
  "Cardiff",
  "Carlisle",
  "Carlsbad",
  "Carmel-by-the-Sea",
  "Carpi",
  "Carpinteria",
  "Carrara",
  "Carson City",
  "Cartagena (Colombia)",
  "Cartagena (Spain)",
  "Casablanca",
  "Caserta",
  "Casper",
  "Cassis",
  "Castellón de la Plana",
  "Castelrotto",
  "Castletown",
  "Castries",
  "Catania",
  "Catanzaro",
  "Caxias do Sul",
  "Cayenne",
  "Cedar Rapids",
  "Celle",
  "Cervinia",
  "Cesena",
  "Český Krumlov",
  "Çeşme",
  "Chamonix",
  "Chandler",
  "Chania",
  "Charleroi",
  "Charleston (West Virginia)",
  "Charleston (South Carolina)",
  "Charlestown",
  "Charlotte",
  "Charlotte Amalie",
  "Charlottetown",
  "Chartres",
  "Chattanooga",
  "Chelmsford",
  "Chemnitz",
  "Chennai",
  "Cherbourg",
  "Chesapeake",
  "Chester",
  "Cheyenne",
  "Chiang Mai",
  "Chiang Rai",
  "Chiavari",
  "Chicago",
  "Chichester",
  "Chieti",
  "Chincoteague",
  "Chioggia",
  "Chios",
  "Chișinău",
  "Chonburi",
  "Christchurch",
  "Christiansted",
  "Chula Vista",
  "Chur",
  "Cincinnati",
  "Ciutadella de Menorca",
  "Civitavecchia",
  "Clarksville",
  "Clearwater",
  "Clermont-Ferrand",
  "Cleveland",
  "Cockburn Town",
  "Cocoa Beach",
  "Coconut Creek",
  "Coimbra",
  "Collioure",
  "Colmar",
  "Cologne",
  "Colombo",
  "Colón",
  "Colorado Springs",
  "Columbia (South Carolina)",
  "Columbia (Missouri)",
  "Columbus",
  "Como",
  "Conakry",
  "Concepción",
  "Concord",
  "Conil de la Frontera",
  "Conway",
  "Copenhagen",
  "Coral Springs",
  "Córdoba (Argentina)",
  "Córdoba (Spain)",
  "Corfu",
  "Corinth",
  "Cork",
  "Corpus Christi",
  "Corralejo",
  "Cortina d'Ampezzo",
  "Cosenza",
  "Costa Adeje",
  "Cottbus",
  "Courchevel",
  "Courmayeur",
  "Coventry",
  "Covington",
  "Coyhaique",
  "Cozumel",
  "Crans-Montana",
  "Cremona",
  "Crotone",
  "Cruz Bay",
  "Cuenca (Ecuador)",
  "Cuenca (Spain)",
  "Cuneo",
  "Da Nang",
  "Dachau",
  "Dakar",
  "Dallas",
  "Damascus",
  "Dana Point",
  "Dar es Salaam",
  "Darmstadt",
  "Darwin",
  "Daugavpils",
  "Dauphin Island",
  "Davenport",
  "Davos",
  "Dayton",
  "Daytona Beach",
  "Deauville",
  "Decatur",
  "Deerfield Beach",
  "Del Mar",
  "Delft",
  "Delhi",
  "Delray Beach",
  "Den Bosch",
  "Denia",
  "Denton",
  "Denver",
  "Derby",
  "Derry",
  "Des Moines",
  "Detroit",
  "Dhaka",
  "Didim",
  "Dieppe",
  "Dijon",
  "Dili",
  "Djibouti",
  "Dodoma",
  "Doha",
  "Dolomiti Superski",
  "Dordrecht",
  "Dorfgastein",
  "Dortmund",
  "Dothan",
  "Douala",
  "Douglas",
  "Dover (Delaware)",
  "Dover (New Hampshire)",
  "Dresden",
  "Dubai",
  "Dublin",
  "Dubrovnik",
  "Duisburg",
  "Duluth",
  "Dundalk",
  "Dundee",
  "Dunedin",
  "Dunkirk",
  "Durham (UK)",
  "Durham (U.S.)",
  "Dushanbe",
  "Düsseldorf",
  "Eastbourne",
  "Eau Claire",
  "Edgartown",
  "Edinburgh",
  "Edmonton",
  "Eilat",
  "Eindhoven",
  "El Paso",
  "Elche",
  "Elizabeth",
  "Elko",
  "Ellmau",
  "Elm",
  "Empuriabrava",
  "Encinitas",
  "Engelberg",
  "Enna",
  "Enschede",
  "Épinal",
  "Erfurt",
  "Erie",
  "Erlangen",
  "Esbjerg",
  "Espace Killy",
  "Essaouira",
  "Essen",
  "Estepona",
  "Eugene",
  "Eureka",
  "Evansville",
  "Everett",
  "Exeter",
  "Èze",
  "Faenza",
  "Fairbanks",
  "Fakaofo",
  "Falmouth",
  "Famagusta",
  "Fano",
  "Fargo",
  "Faro",
  "Fayetteville (North Carolina)",
  "Fayetteville (Arkansas)",
  "Fermo",
  "Fernandina Beach",
  "Ferrara",
  "Fethiye",
  "Fez",
  "Fieberbrunn",
  "Filzmoos",
  "Finale Ligure",
  "Fiumicino",
  "Flagstaff",
  "Flaine",
  "Flint",
  "Florence",
  "Florence (Alabama)",
  "Foggia",
  "Folgarida",
  "Fontana",
  "Forlì",
  "Fort Collins",
  "Fort Lauderdale",
  "Fort Myers",
  "Fort Smith",
  "Fort Wayne",
  "Fort Worth",
  "Fort-de-France",
  "Forte dei Marmi",
  "Foz do Iguaçu",
  "Frankfort",
  "Frankfurt am Main",
  "Franklin",
  "Frederick",
  "Fredericton",
  "Frederiksted",
  "Freeport",
  "Freetown",
  "Freiburg",
  "Fremont",
  "Fresno",
  "Fribourg",
  "Frosinone",
  "Fuengirola",
  "Fujairah",
  "Fukuoka",
  "Funafuti",
  "Funchal",
  "Gaborone",
  "Gainesville",
  "Galtür",
  "Galway",
  "Gandia",
  "Garden Grove",
  "Garland",
  "Gastonia",
  "Gatineau",
  "Gaza City",
  "Gdansk",
  "Gdynia",
  "Geelong",
  "Gelsenkirchen",
  "Geneva",
  "Genoa",
  "George Town (Cayman Islands)",
  "George Town (Malaysia)",
  "Georgetown",
  "Ghent",
  "Gijón",
  "Gilbert",
  "Girona",
  "Gitega",
  "Glasgow",
  "Glendale (Arizona)",
  "Glendale (California)",
  "Gloucester",
  "Gold Coast",
  "Gorizia",
  "Dachstein-West",
  "Gothenburg",
  "Göttingen",
  "Gouda",
  "Granada",
  "Grand Forks",
  "Grand Island",
  "Grand Junction",
  "Grand Prairie",
  "Grand Rapids",
  "Granville",
  "Grasse",
  "Graz",
  "Great Falls",
  "Greeley",
  "Green Bay",
  "Greensboro",
  "Greenville NC",
  "Greenville SC",
  "Grenoble",
  "Grindelwald",
  "Groningen",
  "Grossarl",
  "Grosseto",
  "Grover Beach",
  "Gstaad",
  "Guadalajara",
  "Guadalupe",
  "Guangzhou",
  "Guayaquil",
  "Guimarães",
  "Gulf Shores",
  "Gulfport",
  "Gustavia",
  "Haarlem",
  "Haifa",
  "Half Moon Bay",
  "Halifax",
  "Halle",
  "Hamburg",
  "Hamilton (Bermuda)",
  "Hamilton (Canada)",
  "Hamilton (New Zealand)",
  "Hampton",
  "Hanford",
  "Hangzhou",
  "Hannover",
  "Hanoi",
  "Harare",
  "Hargeisa",
  "Harrisburg",
  "Hartford",
  "Hasselt",
  "Hastings",
  "Hat Yai",
  "Hattiesburg",
  "Havana",
  "Heidelberg",
  "Heilbronn",
  "Heiligenblut",
  "Helena",
  "Helsinki",
  "Henderson",
  "Heraklion",
  "Herceg Novi",
  "Hereford",
  "Hermosa Beach",
  "Hervey Bay",
  "Hialeah",
  "Hillsboro",
  "Hinterglemm",
  "Hinterstoder",
  "Hiroshima",
  "Hoi An",
  "Hobart",
  "Ho Chi Minh City",
  "Holbrook",
  "Hollywood (Florida)",
  "Honfleur",
  "Hong Kong",
  "Honiara",
  "Honolulu",
  "Horsens",
  "Hot Springs",
  "Houston",
  "Hua Hin",
  "Hue",
  "Huntington",
  "Huntington Beach",
  "Huntsville",
  "Hvar",
  "Hyères",
  "Ibiza Town",
  "Imola",
  "Imperia",
  "Inca",
  "Indianapolis",
  "Ingolstadt",
  "Innsbruck",
  "Interlaken",
  "Inverness",
  "Ioannina",
  "Iqaluit",
  "Irvine",
  "Irving",
  "Ischgl",
  "Isernia",
  "Lahore",
  "Islamorada",
  "Istanbul",
  "İzmir",
  "Izola",
  "Jackson",
  "Jackson (Tennessee)",
  "Jacksonville",
  "Jaipur",
  "Jefferson City",
  "Jena",
  "Jerez de la Frontera",
  "Jersey City",
  "Jerusalem",
  "Johannesburg",
  "Johnson City",
  "Joinville",
  "Jonesboro",
  "Juan-les-Pins",
  "Juba",
  "Juiz de Fora",
  "Juneau",
  "Jungfrau",
  "Jupiter",
  "Jūrmala",
  "Kabul",
  "Kaiserslautern",
  "Kalamata",
  "Kalamazoo",
  "Kampala",
  "Kanchanaburi",
  "Kansas City",
  "Kansas City (Kansas)",
  "Kappl",
  "Kaprun",
  "Islamabad",
  "Karlovy Vary",
  "Karlsruhe",
  "Kassel",
  "Kastoria",
  "Kathmandu",
  "Kaunas",
  "Kavala",
  "Kearney",
  "Keene",
  "Kemer",
  "Kenosha",
  "Key Largo",
  "Key West",
  "Khao Lak",
  "Khartoum",
  "Kiel",
  "Kigali",
  "Kilkenny",
  "Kingman",
  "Kingston (Jamaica)",
  "Kingston (Norfolk Island)",
  "Kingston upon Hull",
  "Kingstown",
  "Kinshasa",
  "Kissimmee",
  "Kitzbühel",
  "Klagenfurt",
  "Klaipėda",
  "Knoxville",
  "Kobe",
  "Koblenz",
  "Kolding",
  "Kolkata",
  "Komotini",
  "Koper",
  "Koror",
  "Kos",
  "Košice",
  "Kotor",
  "Krabi",
  "Krakow",
  "Kralendijk",
  "Krefeld",
  "Kuah",
  "Kuala Lumpur",
  "Kuşadası",
  "Kutná Hora",
  "Kuwait City",
  "Kyiv",
  "Kyoto",
  "Kyrenia",
  "La Ciotat",
  "La Clusaz",
  "La Laguna",
  "La Maddalena",
  "La Manga",
  "La Paz",
  "La Plagne",
  "La Plata",
  "La Rochelle",
  "La Romana",
  "La Serena",
  "La Spezia",
  "La Thuile",
  "Laax",
  "Lafayette (Indiana)",
  "Lafayette (Louisiana)",
  "Lagos (Nigeria)",
  "Lagos (Portugal)",
  "Laguna Beach",
  "Karachi",
  "Lakeland",
  "Lalitpur",
  "Lamezia Terme",
  "Lancaster",
  "Lancaster (U.S.)",
  "Landshut",
  "Lansing",
  "L'Aquila",
  "Laredo",
  "Largo",
  "Larnaca",
  "Las Cruces",
  "Las Palmas",
  "Las Vegas",
  "Latina",
  "Lausanne",
  "Laval",
  "Lawton",
  "Layton",
  "Le Havre",
  "Le Lavandou",
  "Le Mans",
  "Lecce",
  "Lecco",
  "Lech",
  "Leeds",
  "Legnano",
  "Leicester",
  "Leiden",
  "Leipzig",
  "Lemgo",
  "Leogang",
  "Les Arcs",
  "Les Deux Alpes",
  "Les Gets",
  "Les Houches",
  "Les Menuires",
  "Leuven",
  "Leverkusen",
  "Lexington",
  "Liberec",
  "Libreville",
  "Lichfield",
  "Liège",
  "Lienz",
  "Liepāja",
  "Lille",
  "Lilongwe",
  "Limassol",
  "Limerick",
  "Limoges",
  "Lincoln",
  "Lincoln",
  "Lindos",
  "Linz",
  "Lisbon",
  "Lisburn",
  "Little Rock",
  "Liverpool",
  "Livigno",
  "Livorno",
  "Ljubljana",
  "Lloret de Mar",
  "Llucmajor",
  "Loano",
  "Locarno",
  "Lodi",
  "Lodz",
  "Logan",
  "Logroño",
  "Lomé",
  "London (Canada)",
  "London (UK)",
  "Londrina",
  "Long Beach",
  "Long Beach (New York)",
  "Long Branch",
  "Longview (Texas)",
  "Longview (Washington)",
  "Lorain",
  "Los Alamos",
  "Los Angeles",
  "Los Cabos",
  "Los Cristianos",
  "Louisville",
  "Lourdes",
  "Loutraki",
  "Louvain-la-Neuve",
  "Lowell",
  "Luanda",
  "Lubbock",
  "Lübeck",
  "Lublin",
  "Lucca",
  "Lucerne",
  "Lugano",
  "Luganville",
  "Lund",
  "Lusaka",
  "Luxembourg",
  "Lyon",
  "Maastricht",
  "Macerata",
  "Macon",
  "Madera",
  "Madison",
  "Madonna di Campiglio",
  "Madrid",
  "Magaluf",
  "Magdeburg",
  "Mahón",
  "Mainz",
  "Majuro",
  "Makarska",
  "Malabo",
  "Malaga",
  "Malé",
  "Malia",
  "Malibu",
  "Malmö",
  "Manacor",
  "Manama",
  "Manchester (UK)",
  "Manchester (U.S.)",
  "Manhattan Beach",
  "Manhattan, KS",
  "Mannheim",
  "Manosque",
  "Mantua",
  "Maputo",
  "Mar del Plata",
  "Marathon",
  "Marbella",
  "Maria Alm",
  "Maribor",
  "Marigot",
  "Markham",
  "Marmaris",
  "Maroochydore",
  "Marquette",
  "Marrakesh",
  "Marsala",
  "Marseille",
  "Martigues",
  "Maseru",
  "Maspalomas",
  "Massa",
  "Matera",
  "Mayrhofen",
  "Mazara del Vallo",
  "Mbabane",
  "McKinney",
  "Mechelen",
  "Medellín",
  "Medford",
  "Megève",
  "Melbourne (Australia)",
  "Melbourne (U.S.)",
  "Memphis",
  "Menton",
  "Merano",
  "Merced",
  "Meribel",
  "Mérida",
  "Meridian",
  "Mesa",
  "Messina",
  "Mestre",
  "Metz",
  "Mexico City",
  "Miami",
  "Middelburg",
  "Midland",
  "Mijas",
  "Milan",
  "Milford",
  "Millau",
  "Milwaukee",
  "Mindelo",
  "Minneapolis",
  "Minot",
  "Minsk",
  "Miramar",
  "Mishawaka",
  "Mississauga",
  "Missoula",
  "Moab",
  "Mobile",
  "Modena",
  "Modesto",
  "Modica",
  "Moena",
  "Mogadishu",
  "Mogi das Cruzes",
  "Mombasa",
  "Monaco City",
  "Mönchengladbach",
  "Monrovia (Liberia)",
  "Monrovia (U.S.)",
  "Mons",
  "Monschau",
  "Monte Carlo",
  "Monte Rosa",
  "Montego Bay",
  "Montepulciano",
  "Monterey",
  "Montgomery",
  "Montluçon",
  "Montpelier",
  "Montpellier",
  "Montreal",
  "Montreux",
  "Monza",
  "Moraira",
  "Moreno Valley",
  "Morgantown",
  "Moroni",
  "Morro Bay",
  "Morzine",
  "Moscow",
  "Mount Vernon",
  "Mountain View",
  "Moutier",
  "Mulhouse",
  "Mumbai",
  "Munich",
  "Münster",
  "Murcia",
  "Murfreesboro",
  "Murter",
  "Mykonos",
  "Mytilene",
  "Nafplio",
  "Nagoya",
  "Nags Head",
  "Nairobi",
  "Namur",
  "Nancy",
  "Nantes",
  "Napa",
  "Naples (Italy)",
  "Naples (U.S.)",
  "Narbonne",
  "Narva",
  "Nashua",
  "Nashville",
  "Nassau",
  "Naxos",
  "Nazareth",
  "N'Djamena",
  "Negril",
  "Neiafu",
  "Nelson",
  "Nerja",
  "Netanya",
  "Nevers",
  "New Haven",
  "New London",
  "New Orleans",
  "New Smyrna Beach",
  "New York City",
  "Newark",
  "Newcastle (Australia)",
  "Newcastle (UK)",
  "Newport (UK)",
  "Newport (Rhode Island)",
  "Newport (Vermont)",
  "Newport Beach",
  "Newport News",
  "Newry",
  "Ngerulmud",
  "Nha Trang",
  "Niagara Falls",
  "Niamey",
  "Nice",
  "Nicosia",
  "Nijmegen",
  "Nimes",
  "Niort",
  "Noosa Heads",
  "Norfolk",
  "Normal",
  "Norman",
  "North Las Vegas",
  "North Port",
  "Norwalk",
  "Norwich",
  "Nottingham",
  "Nouakchott",
  "Novara",
  "Novigrad",
  "Nukunonu",
  "Nukuʻalofa",
  "Nuoro",
  "Nürnberg",
  "Nur-Sultan",
  "Nuuk",
  "Nyon",
  "Oakland",
  "Oaxaca",
  "Obergurgl",
  "Oberhausen",
  "Ocala",
  "Ocean City",
  "Ocean Grove",
  "Oceanside",
  "Ocho Rios",
  "Odense",
  "Odessa",
  "Ogden",
  "Oia",
  "Oklahoma City",
  "Olbia",
  "Oldenburg",
  "Olomouc",
  "Olympia",
  "Omaha",
  "Opatija",
  "Orange Beach",
  "Oranjestad (Aruba)",
  "Oranjestad (Sint Eustatius)",
  "Orem",
  "Oristano",
  "Orlando",
  "Orléans",
  "Ortisei",
  "Osaka",
  "Oshkosh",
  "Oslo",
  "Osnabrück",
  "Ostrava",
  "Ottawa",
  "Ouagadougou",
  "Oulu",
  "Ourense",
  "Overland Park",
  "Oviedo",
  "Owensboro",
  "Oxford",
  "Oxnard",
  "Pacific Grove",
  "Paderborn",
  "Padova",
  "Pago Pago",
  "Palanga",
  "Palavas-les-Flots",
  "Palermo",
  "Palikir",
  "Palm Bay",
  "Palm Beach",
  "Palm Springs",
  "Palma de Mallorca",
  "Palma Nova",
  "Palmetto",
  "Palo Alto",
  "Pamplona",
  "Panama City (Panama)",
  "Panama City (U.S.)",
  "Paphos",
  "Paradiski",
  "Paralia",
  "Paramaribo",
  "Parikia",
  "Paris",
  "Parkersburg",
  "Parma",
  "Pärnu",
  "Pasadena",
  "Passo del Tonale",
  "Passo Rolle",
  "Paterson",
  "Patras",
  "Pattaya",
  "Pau",
  "Pavia",
  "Peel",
  "Peguera",
  "Pembroke Pines",
  "Peniscola",
  "Pensacola",
  "Peoria",
  "Perast",
  "Périgueux",
  "Perpignan",
  "Perros-Guirec",
  "Perth (Australia)",
  "Perth (UK)",
  "Perugia",
  "Pesaro",
  "Pescara",
  "Pescasseroli",
  "Petah Tikva",
  "Peterborough",
  "Petra",
  "Petrovac",
  "Pforzheim",
  "Phang Nga",
  "Phetchabun",
  "Philadelphia",
  "Philipsburg",
  "Phoenix",
  "Phuket City",
  "Piacenza",
  "Pierre",
  "Pine Bluff",
  "Piraeus",
  "Piran",
  "Pisa",
  "Pistoia",
  "Pittsburgh",
  "Placencia",
  "Plano",
  "Playa Blanca",
  "Playa de las Américas",
  "Playa del Carmen",
  "Pleasure Point",
  "Plovdiv",
  "Plymouth",
  "Plzeň",
  "Podgorica",
  "Pointe-à-Pitre",
  "Poitiers",
  "Pollença",
  "Pompano Beach",
  "Pontevedra",
  "Pordenone",
  "Poreč",
  "Port Angeles",
  "Port Charlotte",
  "Port d'Andratx",
  "Port Louis",
  "Port Moresby",
  "Port of Spain",
  "Port St. Lucie",
  "Port Townsend",
  "Port Vila",
  "Port-au-Prince",
  "Portimão",
  "Portland (Oregon)",
  "Portland (Maine)",
  "Porto",
  "Porto Cervo",
  "Porto Cristo",
  "Porto Torres",
  "Portocolom",
  "Portofino",
  "Porto-Novo",
  "Portorož",
  "Porto-Vecchio",
  "Portsmouth (UK)",
  "Portsmouth (U.S.)",
  "Positano",
  "Potenza",
  "Potsdam",
  "Poznan",
  "Pozzuoli",
  "Prague",
  "Praia",
  "Praia da Rocha",
  "Prato",
  "Prescott",
  "Preston",
  "Pretoria",
  "Pristina",
  "Propriano",
  "Protaras",
  "Providence",
  "Provo",
  "Pueblo",
  "Puerto Baquerizo Moreno",
  "Puerto de la Cruz",
  "Puerto Plata",
  "Puerto Rico de Gran Canaria",
  "Puerto Vallarta",
  "Pula",
  "Punta Arenas",
  "Punta Cana",
  "Punta Gorda",
  "Pyeongchang",
  "Pyongyang",
  "Quarteira",
  "Quebec",
  "Quimper",
  "Quito",
  "Rabat",
  "Racine",
  "Ragusa",
  "Railay Beach",
  "Raleigh",
  "Ramallah",
  "Ramsey",
  "Rancho Cucamonga",
  "Randers",
  "Rapallo",
  "Rapid City",
  "Ras al-Khaimah",
  "Ratingen",
  "Ravello",
  "Ravenna",
  "Rayong",
  "Reading",
  "Redding",
  "Redondo Beach",
  "Regensburg",
  "Reggio Calabria",
  "Reggio Emilia",
  "Regina",
  "Rehovot",
  "Reims",
  "Rennes",
  "Reno",
  "Rethymno",
  "Reus",
  "Reutlingen",
  "Reykjavik",
  "Rhodes",
  "Richmond",
  "Rieti",
  "Riga",
  "Rijeka",
  "Rimini",
  "Rio de Janeiro",
  "Riomaggiore",
  "Rishon LeZion",
  "Riverside",
  "Riviera Maya",
  "Road Town",
  "Roanoke",
  "Rocamadour",
  "Rochester (Minnesota)",
  "Rochester (New York)",
  "Rock Hill",
  "Rockford",
  "Rockville",
  "Rodez",
  "Rogers",
  "Rome",
  "Ronda",
  "Rosario",
  "Roseau",
  "Roskilde",
  "Rostock",
  "Roswell",
  "Rotterdam",
  "Roubaix",
  "Rouen",
  "Rovigo",
  "Rovinj",
  "Rutland",
  "Sa Coma",
  "Sa Pobla",
  "Saalbach",
  "Saarbrücken",
  "Saas-Fee",
  "Sacramento",
  "Saint Paul",
  "Saint Petersburg",
  "Saint-Brieuc",
  "Sainte-Maxime",
  "Saintes-Maries-de-la-Mer",
  "Saint-Étienne",
  "Saint-Jean-Cap-Ferrat",
  "Saint-Laurent-du-Maroni",
  "Saint-Malo",
  "Saint-Tropez",
  "Salamanca",
  "Salem (Oregon)",
  "Salem (Massachusetts)",
  "Salerno",
  "Salinas",
  "Salisbury",
  "Salou",
  "Salt Lake City",
  "Salta",
  "Salvador",
  "Salzburg",
  "Samaná",
  "San Angelo",
  "San Antonio",
  "San Bernardino",
  "San Clemente",
  "San Diego",
  "San Francisco",
  "San José (Costa Rica)",
  "San Jose (U.S.)",
  "San Juan",
  "San Luis Obispo",
  "San Marino",
  "San Mateo",
  "San Pedro",
  "San Pedro de Atacama",
  "San Rafael",
  "San Sebastián",
  "Sanaa",
  "Sanford",
  "Sanremo",
  "Sant Antoni de Portmany",
  "Santa Ana",
  "Santa Barbara",
  "Santa Clara",
  "Santa Clarita",
  "Santa Cruz",
  "Santa Cruz de la Sierra",
  "Santa Cruz de Tenerife",
  "Santa Eulària des Riu",
  "Santa Fe",
  "Santa Margherita Ligure",
  "Santa Maria (Cape Verde)",
  "Santa Maria (U.S.)",
  "Santa Monica",
  "Santa Pola",
  "Santa Ponsa",
  "Santa Rosa",
  "Santander",
  "Santanyí",
  "Santiago (Chile)",
  "Santiago (Dominican Rep.)",
  "Santiago de Compostela",
  "Santo Domingo",
  "Sao Paulo",
  "São Tomé",
  "Sapporo",
  "Sarajevo",
  "Sarasota",
  "Saratoga Springs",
  "S'Arenal",
  "Sarlat-la-Canéda",
  "Saskatoon",
  "Sassari",
  "Saumur",
  "Savannah",
  "Savona",
  "Schaffhausen",
  "Schenectady",
  "Schladming",
  "Scottsdale",
  "Scranton",
  "Sea Isle City",
  "Seal Beach",
  "Seaside",
  "Seattle",
  "Sedona",
  "Seefeld",
  "Segovia",
  "Seoul",
  "Serre Chevalier",
  "Sète",
  "Seville",
  "Shanghai",
  "Sharjah",
  "Sheffield",
  "Shenzhen",
  "Shreveport",
  "Šiauliai",
  "Šibenik",
  "Side",
  "Siegen",
  "Siena",
  "Sineu",
  "Singapore",
  "Sion",
  "Sioux City",
  "Sioux Falls",
  "Sitges",
  "Skiathos",
  "Skopje",
  "Sofia",
  "Sölden",
  "Söll",
  "Soller",
  "Solothurn",
  "Sondrio",
  "Sopot",
  "Sorocaba",
  "Sorrento",
  "South Bend",
  "Southampton",
  "Split",
  "Spokane",
  "Springdale",
  "Springfield (Illinois)",
  "Springfield (Massachusetts)",
  "Springfield (Missouri)",
  "Springfield (Oregon)",
  "St Albans",
  "St George's (Bermuda)",
  "St. Albans",
  "St. Anton",
  "St. Augustine",
  "St. Cloud",
  "St. Gallen",
  "St. George",
  "St. George's (Grenada)",
  "St. John's (Antigua and Barbuda)",
  "St. John's (Canada)",
  "St. Louis",
  "St. Moritz",
  "St. Petersburg (U.S.)",
  "Stamford",
  "Stanley",
  "Stavanger",
  "Stillwater",
  "Stirling",
  "Stockholm",
  "Stockton",
  "Stoke-on-Trent",
  "Stone Harbor",
  "Strasbourg",
  "Stuttgart",
  "Sucre",
  "Sukhothai",
  "Sumter",
  "Sunderland",
  "Sunnyvale",
  "Sunshine Coast",
  "Superior",
  "Surrey",
  "Sveti Stefan",
  "Swansea",
  "Sydney",
  "Syracuse (Italy)",
  "Syracuse (U.S.)",
  "Szczecin",
  "Tacoma",
  "Taipei",
  "Tallahassee",
  "Tallinn",
  "Tampa",
  "Tampere",
  "Tamworth",
  "Tangier",
  "Taormina",
  "Taranto",
  "Tarifa",
  "Tarragona",
  "Tartu",
  "Tashkent",
  "Tauplitz",
  "Tauranga",
  "Tavira",
  "Tbilisi",
  "Tel Aviv",
  "Temecula",
  "Tempe",
  "Teramo",
  "Terni",
  "Texarkana AR",
  "Texarkana TX",
  "The Bottom",
  "The Hague",
  "The Valley",
  "The Woodlands",
  "Thessaloniki",
  "Thimphu",
  "Tignes",
  "Tijuana",
  "Tilburg",
  "Tinos",
  "Tirana",
  "Tivat",
  "Tivoli",
  "Tokyo",
  "Toledo (Spain)",
  "Toledo (U.S.)",
  "Tooele",
  "Toowoomba",
  "Topeka",
  "Toronto",
  "Torre del Greco",
  "Torre del Mar",
  "Torremolinos",
  "Torrevieja",
  "Tórshavn",
  "Toruń",
  "Tossa de Mar",
  "Toulon",
  "Toulouse",
  "Tours",
  "Townsville",
  "Trani",
  "Trapani",
  "Trento",
  "Trenton",
  "Treviso",
  "Trier",
  "Trieste",
  "Tripoli",
  "Trogir",
  "Tromsø",
  "Trondheim",
  "Trouville-sur-Mer",
  "Troy",
  "Troyes",
  "Tucson",
  "Tui",
  "Tulsa",
  "Tulum",
  "Turin",
  "Turku",
  "Tuscaloosa",
  "Twin Falls",
  "Two Harbors",
  "Tybee Island",
  "Tyler",
  "Udine",
  "Udon Thani",
  "Ukiah",
  "Ulaanbaatar",
  "Ulcinj",
  "Ulm",
  "Umag",
  "Uppsala",
  "Urbino",
  "Ushuaia",
  "Utica",
  "Utrecht",
  "Vaduz",
  "Val d’Isère",
  "Val di Fassa",
  "Val Gardena",
  "Val Thorens",
  "Valence",
  "Valencia",
  "Valladolid",
  "Valldemossa",
  "Valle Isarco",
  "Valletta",
  "Valparaíso",
  "Vancouver (Canada)",
  "Vancouver (U.S.)",
  "Varazze",
  "Varese",
  "Varna",
  "Vaughan",
  "Vejle",
  "Venice (Italy)",
  "Venice (U.S.)",
  "Ventimiglia",
  "Ventspils",
  "Ventura",
  "Verbania",
  "Verbier",
  "Vercelli",
  "Vero Beach",
  "Verona",
  "Versailles",
  "Vevey",
  "Viareggio",
  "Vibo Valentia",
  "Viborg",
  "Vicenza",
  "Vichy",
  "Victoria (Canada)",
  "Victoria (Seychelles)",
  "Victorville",
  "Vienna",
  "Vigo",
  "Vilamoura",
  "Villach",
  "Villefranche-sur-Mer",
  "Vilnius",
  "Viña del Mar",
  "Virginia Beach",
  "Visalia",
  "Viterbo",
  "Vitoria-Gasteiz",
  "Volos",
  "Vrsar",
  "Waco",
  "Wakefield",
  "Warsaw",
  "Warth",
  "Washington D.C.",
  "Waterford",
  "Watertown",
  "Watsonville",
  "Waukegan",
  "Waukesha",
  "Wellington (New Zealand)",
  "Wellington (U.S.)",
  "Wengen",
  "Weno",
  "West Lafayette",
  "West Palm Beach",
  "Westendorf",
  "Westminster",
  "Weston",
  "Wheeling",
  "White Plains",
  "Whitehorse",
  "Wichita",
  "Wichita Falls",
  "Wiesbaden",
  "Wildwood",
  "Wilkes-Barre",
  "Willemstad",
  "Williams",
  "Wilmington (Delaware)",
  "Wilmington (North Carolina)",
  "Winchester",
  "Windhoek",
  "Windsor",
  "Winnipeg",
  "Winslow",
  "Winston–Salem",
  "Winterthur",
  "Wolfsburg",
  "Wollongong",
  "Wolverhampton",
  "Woodburn",
  "Worcester (UK)",
  "Worcester (U.S.)",
  "Worthing",
  "Wroclaw",
  "Wuppertal",
  "Würzburg",
  "Yakima",
  "Yamoussoukro",
  "Yaoundé",
  "Yaren",
  "Yellowknife",
  "Yerevan",
  "Yokohama",
  "Yonkers",
  "York (UK)",
  "York (U.S.)",
  "Youngstown",
  "Yuma",
  "Zadar",
  "Zagreb",
  "Zakopane",
  "Zanzibar",
  "Zaragoza",
  "Zell am See",
  "Zell am Ziller",
  "Zermatt",
  "Zug",
  "Zurich",
  "Zwickau",
  "Zwolle",
  ]
end
